services:
  authenticator:
    image: jpkitt/authenticator:latest
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /model/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  admin:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped